### ISSUE TITLE
Redesign

### ISSUE THREAD

**Issue by julianrichen** [GabMus/razerCommander#1]
Hello,
I don't own a Razer device but was impressed by your work, thank you for making a re-implantation of something that will probably never be ported to Linux.

I wanted to provide some suggestions on improving the ui.
![razercommander - redesign 0 1](https://cloud.githubusercontent.com/assets/58045/16715197/99e242c0-46a7-11e6-9466-c48f9ae13e6c.png)

The main changes are:
- The layout, adding spacing to improve readability
- Using a single "Apply" button instead of two
- Move the game mode switch to the header bar saving space in the application
- Using a headerbar pop-over for the devices instead of a dropdown box.

You could also make the Breath Mode section a combo box/pop-over to save more room for more features later on.

You can view the original [svg here](http://dl.richen.io/gnome/razerCommander/razerCommander.svg)

**Comment by GabMus** [comment]
This is a really nice design, thank you! This is actually a great contributrion, and that's what I was hoping to get!
I love it, I'm implementing it right now!

**Comment by GabMus** [comment]
It's done! I'm pushing the changes in like 1 minute

**Comment by julianrichen** [comment]
Damn that was fast, glad it helped :)

My only other suggestion would be to use a consistent padding. I believe GNOME uses 7px (or 10px) for almost everything with extra padding being multiples of 7, 14px, 21px, etc...

Oh and I just realized your the owner of TechPill, I actually found this app from your channel but I didn't connect the two. Thanks for promoting Linux.
