### ISSUE TITLE
Problem after last update

### ISSUE THREAD

**Issue by AGPDev** [GabMus/razerCommander#15]
After update razerCommander not open anymore

![razercommander](https://cloud.githubusercontent.com/assets/5721341/20563866/878e7bfe-b171-11e6-8bfe-f32a77c4bd66.png)

I remove the tabs and change for spaces, this work.

**Comment by GabMus** [comment]
Thanks for reporting, please try with the latest version and tell me if it
still happens

**Comment by AGPDev** [comment]
Perfect, thanks
