### ISSUE TITLE
Error thrown if no Razor driver is installed

### ISSUE THREAD

**Issue by julianrichen** [GabMus/razerCommander#2]
The likelihood this will happen to most users is rare but if you don't have the Razer driver installed it throws an error:

```
$ ./main.py 
Traceback (most recent call last):
  File "./main.py", line 56, in <module>
    initDevices()
  File "./main.py", line 29, in initDevices
    cont=os.listdir(device.Device.DRIVER_PATH)
FileNotFoundError: [Errno 2] No such file or directory: '/sys/bus/hid/drivers/razerkbd/'
```

Might be better to warn the user with a proper message, "No Razor driver installed, please install the driver before running this software".

Since I don't own a Razer product it's kind of illogical to run the program but might be nice for other users that do have Razor products and for whatever reason don't have the driver installed.

**Comment by GabMus** [comment]
Oh, yes of course. Gonna add a little dialog at startup if the driver isn't
installed. Thanks for reporting
