### ISSUE TITLE
dBus throwing exceptions

### ISSUE THREAD

**Issue by vitacell** [GabMus/razerCommander#24]
Arch gnulinux:
Linux Maquinon64 4.8.13-1-ARCH #1 SMP PREEMPT Fri Dec 9 07:24:34 CET 2016 x86_64 GNU/Linux

+razer orbveawer and deathadder chroma

The razer-service is always running, already tryed everything. "razercfg" and "razerd" always worked fine. I uninstalled them, but now I am in trouble with all that razer-driver stuff. I can run razerCommander, only DA chroma is detected, and I can see only light value, nothing more, when I apply setting (even nothing is changed), in devices it adds another DA chroma after every apply.

[vita@Maquinon64 ~]$ /usr/bin/razercommander
ERROR:dbus.proxies:Introspect error on :1.53:/org/razer: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
DEBUG:dbus.proxies:Executing introspect queue due to error
Traceback (most recent call last):
  File "/usr/share/razercommander/main.py", line 7, in <module>
    import device
  File "/usr/share/razercommander/device.py", line 10, in <module>
    device_manager = rclient.DeviceManager()
  File "/usr/lib/python3.6/site-packages/razer/client/__init__.py", line 30, in __init__
    self._device_serials = self._dbus_devices.getDevices()
  File "/usr/lib/python3.6/site-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python3.6/site-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
[vita@Maquinon64 ~]$ ps -aux | grep razer-service
vita       975  0.1  0.5 381712 31172 pts/1    Sl+  04:20   0:03 razer-service
vita      1206  0.0  0.0  11052  2192 pts/2    S+   05:05   0:00 grep razer-service

**Comment by GabMus** [comment]
This looks like a daemon issue, you should fill an issue in https://github.com/terrycain/razer-drivers
