### ISSUE TITLE
Error thrown if no supported device is available

### ISSUE THREAD

**Issue by r0l1** [GabMus/razerCommander#3]
I am just working to integrate support for the Razer Blade 2016 keyboard into the razer chroma drivers. I really like your small application! I experienced a crash if no supported device is available...

```
Traceback (most recent call last):
  File "/usr/share/razercommander/main.py", line 61, in <module>
    fillDevicesList()
  File "/usr/share/razercommander/main.py", line 56, in fillDevicesList
    popoverDevicesListBox.get_row_at_index(0).value.name
AttributeError: 'NoneType' object has no attribute 'value'
```

By the way: Great UI design!

**Comment by GabMus** [comment]
Thanks for reporting, it should be fixed now!

> Great UI design!
> Well, thank julianrichen (issue #1) for it! :smile:
