### ISSUE TITLE
Prepare for rename to OpenRazer (2.0.0)

### ISSUE THREAD

**Issue by lah7** [GabMus/razerCommander#41]
**Heads up!** `terrycain/razer-drivers` is now [`openrazer/openrazer`](https://github.com/openrazer/openrazer) with a new version of 2.0.0. Some new packages will be released this week, ideally alongside front-end apps.

* Any Python library imports for `razer` are now `openrazer`.
* For Ubuntu packaging (at least), the packages should depend on `openrazer-daemon`, `python3-openrazer`, etc and not simply `razer-daemon`, `python3-razer` anymore.

**Comment by GabMus** [comment]
Done
