### ISSUE TITLE
deb package installs for python3.6 by default

### ISSUE THREAD

**Issue by charandas** [GabMus/razerCommander#52]
I did not have a straightforward path to the using the deb package. At first, I thought I was missing Python GTK/GObject, but turns out the bootstrap script is using python 3.6 specific stuff such as:

```
sys.path.insert(1, '/usr/lib/python3.6/site-packages')
# and
    gi.require_versions({
        'Gtk': '3.0',
    })
```

My python3.5 package only supported `gi.require_version('Gtk', '3.0')`. So in the spirit of saving time for a non python established end-user, we may wanna recommend a python3.6 [install](https://askubuntu.com/a/865569). Thoughts?

**Comment by GabMus** [comment]
Oh, that's very helpful, thanks! I tested the deb in Ubuntu Mate 17.10 and it worked fine, so I guess it's a problem with older versions that don't ship python 3.6. Will make sure to point out to that link in the Ubuntu sections.
