### ISSUE TITLE
Fix AUR PKGBUILD

### ISSUE THREAD

**Issue by Agrendalath** [GabMus/razerCommander#54]
Could you provide correct $pkgver in [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=razercommander-git) for [AUR package](https://aur.archlinux.org/packages/razercommander-git/)?
Currently pkgver() returns `1.2.0.r6.gefd04b3`, so it always needs to be updated.

**Comment by WhyNotHugo** [comment]
`1.2.0.r6.gefd04b3` is the latest version. The value being returned is correct. What would you expect it to return?

**Comment by Agrendalath** [comment]
Actually, upgrade in `yaourt` looks like this:
```aur/razercommander-git  1.2.0.r6.gefd04b3-1               -> 1.2.0.r31.g760e251-1```

So only the line `pkgver=1.2.0.r31.g760e251` from PKGBUILD is taken into account as newest available version while looking for upgrades. The local one is, of course, `1.2.0.r31.g760e251-1`.

**Comment by GabMus** [comment]
Fixed
