### ISSUE TITLE
Logo wont change colors, deathadder chroma, arch

### ISSUE THREAD

**Issue by bcmmbc122333** [GabMus/razerCommander#56]
For some reason the color wont change for the logo on Arch. Im using a deathadder chroma. the color works on the scroll wheel but the logo doesnt. The effects work for both the scroll wheel and the logo. The only time the logo shows another color is during the spectrum cycle effect, it will start red and fade into to black then fade to blue, then blue will fade into red again and the cycle repeats.

**Comment by GabMus** [comment]
Sounds like the green part of your rgb led is fried. If you can, try the windows driver, if it doesn't work either, RMA it

**Comment by GabMus** [comment]
closed for inactivity, also this is probably hardware related. if I'm wrong, just reopen it
