### ISSUE TITLE
AttributeError: model 'gi'

### ISSUE THREAD

**Issue by tmitzka** [GabMus/razerCommander#58]
I installed version 1.2.0 on Linux Mint. When I start RazerCommander from the menu, nothing happens.

When I start it from the command line, I get the following error message:

```
Traceback (most recent call last):
  File "/usr/bin/razercommander", line 44, in <module>
    gi.require_versions({
AttributeError: module 'gi' has no attribute 'require_versions'
```

**Comment by Xcelled** [comment]
I fixed this by editing `/usr/bin/razercommander`.

I changed the `gi.require_versions` lines to `gi.require_version('Gtk', '3.0')` and it worked after that.

**Comment by tmitzka** [comment]
Now it works. Thanks a lot!

**Comment by Xcelled** [comment]
@Kauri5 this is an actual issue. You should leave it open so it can be fixed.

**Comment by GabMus** [comment]
should work now
