### ISSUE TITLE
Syntax / Property Error

### ISSUE THREAD

**Issue by vozeldr** [GabMus/razerCommander#59]
There is a syntax error on this line with the string formatting. Also, I think because of some of the rewrite, there is no longer a device.name... it's device.device.name. I know you can't really test this particular line without an unsupported device. This replacement for the line should fix the issue.
```
print('Skipping device: {}'.format(device.device.name))
```
https://github.com/GabMus/razerCommander/blob/8160debe84069e026e788d3cd036987572a29f35/razercommander/__main__.py#L250

**Comment by GabMus** [comment]
duplicate of #61 now fixed
