### ISSUE TITLE
I need help downloading the driver and razerCommander

### ISSUE THREAD

**Issue by Kah-leeb** [GabMus/razerCommander#65]
i need help installing the driver and razerCommander and what linux would you recommend i have ubuntu unity btw

**Comment by GabMus** [comment]
- Install openrazer: https://openrazer.github.io/#ubuntu
- Install razercommander: https://github.com/GabMus/razerCommander/releases/tag/1.2.1.1

Everything is clearly explained in the readme, next time try reading through it before opening an issue.

**Comment by Kah-leeb** [comment]
thank you
