### ISSUE TITLE
I need help. My Razer Ornata Chroma is not showing in razerCommander.

### ISSUE THREAD

**Issue by ghost** [GabMus/razerCommander#66]
my device isnt showing in razer commander i got the application and it says no devices connected and i have my razer ornata plugged in. I have installed the application and i dont know what to do from there.

**Comment by GabMus** [comment]
What distro are you running? What version of the driver did you install? How did you install razercommander?

Answer these questions, then open up a terminal, write `razercommander`, press enter and send the output.

**Comment by Kah-leeb** [comment]
OK so i downloaded this on my Ubuntu then i downloaded these 3 links and one of them i clicked on them and it opened an installer for razerCommander then I installed it and I install python 3.6 also

**Comment by ghost** [comment]
OK so I downloaded this on my Ubuntu 16.04 https://openrazer.github.io/#ubuntu then I downloaded these 3 links by clicking them and the links when to my files https://github.com/GabMus/razerCommander/releases/tag/1.2.1.1 and one of them I clicked on them and it opened an installer for razerCommander then I installed it and I also installed python 3.6 and that all I did also when i type in razercommander it says 
 razercommander
Importing device logic, waiting for daemon
Device logic loaded, daemon is alive
no devices
no devices
no devices

**Comment by Kah-leeb** [comment]
hey i did the same thing and it didnt work

**Comment by GabMus** [comment]
@zachary12345678 did you reboot after installing everything?

**Comment by zachary12345678** [comment]
let me try that

**Comment by ghost** [comment]
Original text:

> how do i reboot and did i install everything and i installed by the razercommander_1.2.1.1ubuntu1_all.deb file and i just clicked on it and it installed the i needed i installed everything in the links and the links where put into my files by the way I am sorry if it takes a while for me to respond i have school and and i have to study for finals

***

Edited by GabMus:

How do i reboot?

Did i install everything I needed? I installed ~by~ using the razercommander_1.2.1.1ubuntu1_all.deb file and i just clicked on it and it installed. ~the i needed~ *(???)*

I installed everything in the links and ~the links~ **the files you linked me** ~where put~ **were downloaded** ~into my files~ **on my computer**.

By the way, I am sorry if it takes a while for me to respond: I have school and and i have to study for finals.

**Comment by GabMus** [comment]
> how do i reboot

Power off your computer and turn it back on.

> did i install everything i needed?

If you installed openrazer-drivers, openrazer-daemon and python3-openrazer, yes you did.

> I installed using the razercommander_1.2.1.1ubuntu1_all.deb file

That's correct.

**Comment by ghost** [comment]
So why isn't my razer ornata linking to razerCommander I also did pollychromatic I think that's what's it's called and the same message popped up which was no devices found and I had my razer ornata plugged in

**Comment by GabMus** [comment]
Again, did you reboot after installing the drivers?

**Comment by Kah-leeb** [comment]
Yes

**Comment by ghost** [comment]
Yes I have but who's Kah-leeb and why does he keep on randomly join this conversion and when i said Razer Ornata im sorry i meant Razer Ornata Chroma

**Comment by GabMus** [comment]
He's another user that apparently has the same problem as you.

Anyway, run this command and send over the output: `lsmod | grep razer`

**Comment by GabMus** [comment]
Also @zachary12345678 try using *punctuation* in your comments. Trying to understand any of your comments is a real challenge .

**Comment by ghost** [comment]
OK, I will.

**Comment by ghost** [comment]
OK, I ran the command in Xterm and nothing happened.

**Comment by GabMus** [comment]
Good, this means that you don't have the kernel driver installed. The reason is that you probably don't have the headers for your current kernel, try running this command: `sudo apt install linux-generic linux-headers-generic`.

This command will ask for your password. When you're done, reboot your computer and try opening up razercommander again. If it still doesn't work, do the following:

- run `razercommander` from the terminal again, and post the output here.
- run `lsmod | grep razer` again and post the output here.

**Comment by ghost** [comment]
I ran the commands and downloaded the stuff you told me and nothing has changed it still says no devices connected. Then when I opened Xterm and ran razercommander it opens up and it says 3 or 4 times no devices. Then I type in lsmod | grep razer nothing happens it still says No devices Connected on razercommander.

**Comment by GabMus** [comment]
> I ran the commands and downloaded the stuff you told me

did you reboot after running the command?

**Comment by ghost** [comment]
Yes, I rebooted after running the command. Nothing has changed

**Comment by GabMus** [comment]
Run the following and post the output: `dpkg --list | grep razer`

How did you install the openrazer driver? Using the ppa?

Also, try running `sudo modprobe razerkbd` and the run `razercommander` again from the terminal, post the output of both.

**Comment by zachary12345678** [comment]
When I type in dpkg --list | grep razer in the Xterm it says ii  openrazer-daemon                      2.1.1~ubuntu16.04.1                        amd64        OpenRazer Device Daemon
ii  openrazer-doc                         2.1.1~ubuntu16.04.1                        all          Documentation and examples for the OpenRazer Tools
ii  openrazer-kernel-modules-dkms         2.1.1~ubuntu16.04.1                        amd64        OpenRazer Peripheral Drivers
ii  openrazer-meta                        2.1.1~ubuntu16.04.1                        all          Metapackage for OpenRazer components
ii  python3-openrazer                     2.1.1~ubuntu16.04.1                        all          OpenRazer Python Library
ii  razercommander                        1.2.1.1ubuntu1                             all          Razer device manager for Linux

**Comment by ghost** [comment]
When I run dpkg --list | grep razer it says 
ii  openrazer-daemon                      2.1.1~ubuntu16.04.1
     amd64        OpenRazer Device Daemon
ii  openrazer-doc                         2.1.1~ubuntu16.04.1
    all          Documentation and examples for the OpenRazer Tools
ii  openrazer-kernel-modules-dkms         2.1.1~ubuntu16.04.1
    amd64        OpenRazer Peripheral Drivers
ii  openrazer-meta                        2.1.1~ubuntu16.04.1
     all          Metapackage for OpenRazer components
ii  python3-openrazer                     2.1.1~ubuntu16.04.1
     all          OpenRazer Python Library
ii  razercommander                        1.2.1.1ubuntu1
      all          Razer device manager for Linux

**Comment by ghost** [comment]
I'm sorry I don't know why some of the XTerm code is crossed out

**Comment by ghost** [comment]
And also when I type in sudo modprobe razerkbd it asks for my password and then it says not found in directory /lib/modules/3.8.11

**Comment by GabMus** [comment]
@zachary12345678 Use gnome-terminal instead of xterm and post the full output of those commands

**Comment by ghost** [comment]
When I type gnome-terminal in Xterm it says command not found

**Comment by GabMus** [comment]
Are you sure you are on Ubuntu 16.04?

Post the output of `lsb_release -a`

**Comment by ghost** [comment]
This is what it says when I run the command lsb_release -a 
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial

**Comment by ghost** [comment]
hello?

**Comment by GabMus** [comment]
This looks like either an upstream issue or something wrong you did that I can't see myself. Either way, it's not a razerCommander specific issue, I think you'll have better luck opening an issue on the upstream driver repo: https://github.com/openrazer/openrazer/issues/new
