### ISSUE TITLE
NoReply error

### ISSUE THREAD

**Issue by newchild** [GabMus/razerCommander#8]
I am getting this error:

 ERROR:dbus.proxies:Introspect error on :1.624:/org/razer: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
DEBUG:dbus.proxies:Executing introspect queue due to error

**Comment by GabMus** [comment]
try with `killall razerdaemon` and `razer-service`

**Comment by newchild** [comment]
still the same error :(

**Comment by newchild** [comment]
Driver itself is working tho

**Comment by GabMus** [comment]
What distro are you running? How did you install the driver?

**Comment by terricain** [comment]
Is razerdaemon actually running?

**Comment by GabMus** [comment]
And please, send over the content of ~/.razer-service/logs/razer.log

**Comment by newchild** [comment]
http://hastebin.com/yuqogexani.1c
I guess this is the problem?

**Comment by newchild** [comment]
I am running antergos, followed the official instructions for arch, step for step, listed on the razer driver repo

**Comment by GabMus** [comment]
The logs show that you have no screensaver installed, which doesn't cause any problem, but nothing interesting. What device do you have?

**Comment by newchild** [comment]
Razer blackwidow chroma

**Comment by GabMus** [comment]
i don't honestly know what's going on, I am working in a very similar setup and everything seems to be working fine. install python-notify2 from AUR and reboot. if that doesn't work, contact me on telegram @gabmus tomorrow at 8AM UTC
