### ISSUE TITLE
Translation?

### ISSUE THREAD

**Issue by geordieF** [GabMus/razerCommander#9]
Some of the translations are just weird. It would be nice to also have community translations, but glade may be a problem here. I can do a bit of basic Czech and English. BTW you should change "Pipette" to "eyedropper"

**Comment by GabMus** [comment]
Alright cool. I'll try to implement translations ASAP. If you can roughly
translate in czech (give me couples of <english word>: <czech
translation>)  it'd be nice.
As for english, I thought it was all correct english. Maybe some italian
slipped in the process? Please just tell me if you see any around. About
pipette, I thought it was english, gonna fix that as well 😀

**Comment by geordieF** [comment]
Pipette _is_ an English word, just not the right one here. Had a look into it and Glade actually has support for translations, so later today i'll have a run-through to see if anything else is wrong.

**Comment by geordieF** [comment]
On a different note, instead of clicking a key, we could just make is so you just press that key to toggle select it. It also might be better to get the screenshots with Adwaita/Ambiance as they are what most people are used to.

**Comment by GabMus** [comment]
> instead of clicking a key, we could just make is so you just press that key to toggle select it

Sorry, couls you be more clear?

**Comment by GabMus** [comment]
Closed for inactivity
